name: lucide_icons
description: A Lucide icon library package for Flutter applications. Fork of Feather Icons, open for anyone to contribute icons.
version: 0.0.1
homepage: https://lucide.dev
repository: https://github.com/lucide-icons/lucide

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  recase: ^4.0.0

flutter:
  fonts:
    - family: Lucide
      fonts:
        - asset: assets/lucide.ttf
